version: '3'

services:
  client_web:
    image: client_web
    build:
      context: ./client_web
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - api-server
      - client_mobile
    volumes:
      - apk:/apk

  client_mobile:
    build: ./client_mobile
    volumes:
      - apk:/apk

  api-server:
    image: api-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080

volumes:
  apk:
